### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by lmajano** [sfeldkamp/coldbox-plugin-BCrypt#2]
Hi Seth,

Just wondering if you are accepting pull requests for this module? We have some changes and updates we would like to send your way, if not is it ok to fork?

**Comment by sfeldkamp** [comment]
Yes, I'm accepting pull requests.  If you'd prefer to fork and bring this under Coldbox aegis I'd certainly understand and support that as well.  I'm open to whichever.

**Comment by lmajano** [comment]
No worries. We will send over some pull requests!!
